"""Minimal AIMarket capability provider generated by create-aimarket-agent."""
from __future__ import annotations

import hmac
import os
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from provider_signing import ProviderSigner

app = FastAPI(
    title="__PROJECT_NAME__",
    docs_url=None,
    redoc_url=None,
    openapi_url=None,
)
METIS_ENABLED = __METIS_PYTHON__
SIGNER = ProviderSigner()
PRODUCT_ID = "__PROJECT_SLUG__"
CAPABILITY_ID = "__PROJECT_SLUG__.invoke@v1"


class InvokeInput(BaseModel):
    input: dict = Field(default_factory=dict)
    product_id: str = Field(default=PRODUCT_ID, max_length=128)
    capability_id: str = Field(default=CAPABILITY_ID, max_length=192)


@app.middleware("http")
async def request_boundary(request: Request, call_next):
    response = None
    if request.method == "POST" and request.url.path == "/invoke":
        raw_length = request.headers.get("content-length")
        try:
            length = int(raw_length) if raw_length is not None else -1
        except ValueError:
            length = -1
        if length < 0 or length > 1_048_576:
            response = JSONResponse({"detail": "request body must be 0-1048576 bytes"}, status_code=413)
    if response is None:
        response = await call_next(request)
    response.headers["Cache-Control"] = "no-store"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["X-Frame-Options"] = "DENY"
    return response


@app.get("/health")
def health() -> dict:
    return {"ok": True, "agent": "__PROJECT_SLUG__", "kind": "__AGENT_KIND__",
            "provider_pubkey": SIGNER.public_key_b64}


@app.post("/invoke")
def invoke(request: InvokeInput) -> JSONResponse:
    # Identity belongs to capability.json, not to an untrusted caller. Allowing
    # arbitrary identifiers here would turn this key into a signing oracle for
    # another product or capability that happens to reuse the provider key.
    if not hmac.compare_digest(request.product_id, PRODUCT_ID):
        return JSONResponse({"detail": "product_id does not match this provider"}, status_code=400)
    if not hmac.compare_digest(request.capability_id, CAPABILITY_ID):
        return JSONResponse({"detail": "capability_id does not match this provider"}, status_code=400)
    # Replace this deterministic example with your capability logic.
    result = {"message": "Hello from __PROJECT_NAME__", "received": request.input,
              "verification_requested": METIS_ENABLED}
    return JSONResponse(
        {"success": True, "result": result},
        headers={"X-Provider-Signature": SIGNER.sign_result(
            result,
            capability_id=CAPABILITY_ID,
            product_id=PRODUCT_ID,
            input_payload=request.input,
        )},
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host=os.getenv("HOST", "127.0.0.1"), port=int(os.getenv("PORT", "8080")))
