/** Minimal AIMarket capability provider generated by create-aimarket-agent. */
import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";

import { ProviderSigner } from "./providerSigning.js";

export const PRODUCT_ID = "__PROJECT_SLUG__";
export const CAPABILITY_ID = "__PROJECT_SLUG__.invoke@v1";
export const AGENT_KIND = "__AGENT_KIND__";
export const METIS_ENABLED = __METIS_ENABLED__;

const MAX_BODY_BYTES = 1_048_576;
const MAX_PRODUCT_ID = 128;
const MAX_CAPABILITY_ID = 192;

export const signer = new ProviderSigner();

function matches(candidate: string, expected: string): boolean {
  const left = Buffer.from(candidate, "utf8");
  const right = Buffer.from(expected, "utf8");
  return left.length === right.length && timingSafeEqual(left, right);
}

function send(response: ServerResponse, status: number, body: unknown, headers: Record<string, string> = {}): void {
  const payload = Buffer.from(JSON.stringify(body), "utf8");
  response.writeHead(status, {
    "content-type": "application/json",
    "content-length": String(payload.length),
    "cache-control": "no-store",
    "x-content-type-options": "nosniff",
    "referrer-policy": "no-referrer",
    "x-frame-options": "DENY",
    ...headers,
  });
  response.end(payload);
}

function readBody(request: IncomingMessage): Promise<Buffer | null> {
  const rawLength = request.headers["content-length"];
  const length = typeof rawLength === "string" && /^\d+$/.test(rawLength) ? Number(rawLength) : -1;
  // A body of unknown or oversized length is refused before it is read, which
  // is the same boundary the Python provider enforces.
  if (length < 0 || length > MAX_BODY_BYTES) {
    return Promise.resolve(null);
  }
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let received = 0;
    request.on("data", (chunk: Buffer) => {
      received += chunk.length;
      if (received > MAX_BODY_BYTES || received > length) {
        request.destroy();
        resolve(null);
        return;
      }
      chunks.push(chunk);
    });
    request.on("end", () => resolve(Buffer.concat(chunks)));
    request.on("error", reject);
  });
}

/** Replace this deterministic example with your capability logic. */
export function handleInvoke(input: Record<string, unknown>): Record<string, unknown> {
  return {
    message: "Hello from __PROJECT_NAME__",
    received: input,
    verification_requested: METIS_ENABLED,
  };
}

async function invoke(request: IncomingMessage, response: ServerResponse): Promise<void> {
  const body = await readBody(request);
  if (body === null) {
    send(response, 413, { detail: `request body must be 0-${MAX_BODY_BYTES} bytes` });
    return;
  }
  let parsed: unknown;
  try {
    parsed = body.length === 0 ? {} : JSON.parse(body.toString("utf8"));
  } catch {
    send(response, 422, { detail: "request body must be a JSON object" });
    return;
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    send(response, 422, { detail: "request body must be a JSON object" });
    return;
  }
  const payload = parsed as Record<string, unknown>;
  const input = payload.input ?? {};
  if (typeof input !== "object" || input === null || Array.isArray(input)) {
    send(response, 422, { detail: "input must be a JSON object" });
    return;
  }
  const productId = payload.product_id ?? PRODUCT_ID;
  const capabilityId = payload.capability_id ?? CAPABILITY_ID;
  if (typeof productId !== "string" || productId.length > MAX_PRODUCT_ID) {
    send(response, 422, { detail: `product_id must be a string of at most ${MAX_PRODUCT_ID} characters` });
    return;
  }
  if (typeof capabilityId !== "string" || capabilityId.length > MAX_CAPABILITY_ID) {
    send(response, 422, { detail: `capability_id must be a string of at most ${MAX_CAPABILITY_ID} characters` });
    return;
  }
  // Identity belongs to capability.json, not to an untrusted caller. Allowing
  // arbitrary identifiers here would turn this key into a signing oracle for
  // another product or capability that happens to reuse the provider key.
  if (!matches(productId, PRODUCT_ID)) {
    send(response, 400, { detail: "product_id does not match this provider" });
    return;
  }
  if (!matches(capabilityId, CAPABILITY_ID)) {
    send(response, 400, { detail: "capability_id does not match this provider" });
    return;
  }
  const result = handleInvoke(input as Record<string, unknown>);
  const signature = signer.signResult(result, {
    capabilityId: CAPABILITY_ID,
    productId: PRODUCT_ID,
    input,
  });
  send(response, 200, { success: true, result }, { "x-provider-signature": signature });
}

export function createAgentServer(): Server {
  return createServer((request, response) => {
    void (async () => {
      try {
        if (request.method === "GET" && request.url === "/health") {
          send(response, 200, {
            ok: true,
            agent: PRODUCT_ID,
            kind: AGENT_KIND,
            provider_pubkey: signer.publicKeyBase64,
          });
          return;
        }
        if (request.method === "POST" && request.url === "/invoke") {
          await invoke(request, response);
          return;
        }
        send(response, 404, { detail: "not found" });
      } catch (error) {
        if (!response.headersSent) {
          send(response, 500, { detail: "internal error" });
        }
        console.error(error);
      }
    })();
  });
}

const entryPoint = process.argv[1] ?? "";
if (entryPoint.endsWith("agent.js") || entryPoint.endsWith("agent.ts")) {
  const port = Number(process.env.PORT ?? "8080");
  const host = process.env.HOST ?? "127.0.0.1";
  createAgentServer().listen(port, host, () => {
    console.log(`__PROJECT_NAME__ listening on http://${host}:${port}`);
  });
}
